# Unconditional sampling
defaults:
  - _inference
  - _self_

inference:
  task: unconditional
  ckpt_path: ckpt/se3-fm/hallucination_pdb/2025-01-04_16-01-37/last.ckpt

  samples:
    length_subset: [70, 100, 200, 300]
    samples_per_length: 100
